FROM public.ecr.aws/docker/library/python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./api /app/api

ENV PORT=80
ENV TIMEOUT_KEEP_ALIVE=600
ENV TIMEOUT=600

CMD ["sh", "-c", "uvicorn api.app:app --workers 2 --host 0.0.0.0 --port ${PORT} --timeout-keep-alive ${TIMEOUT_KEEP_ALIVE}"]
